### ISSUE TITLE
A configuration tweak if you're using a gh-pages sub-folde

### ISSUE THREAD

**Issue by jonduan** [johno/pixyll#292]
This is original tweak
You will also need to tweak the "header" include /{{ site.baseurl }}:

```
<header class="site-header px2 px-responsive">
  <div class="mt2 wrap">
    <div class="measure">
      <a href="{{ site.url }}/{{ site.baseurl }}">{{ site.title }}</a>
      <nav class="site-nav right">
        {% include navigation.html %}
      </nav>
    </div>
  </div>
</header>
```
# 

I tried it and found that  

```
<a href="{{ site.url }}{{ site.baseurl }}">{{ site.title }}</a>
```

is fine since {{ site.baseurl }} is already "/" ed .
# 

And another file "navigation.html" is needed to modified accordingly.
# 

Thanks a lot. 

Great theme for Jykell.

I modified my repo, but I am not familiar to pull request. 

Some one can point a link to show how to do it? 

Really appreciated.

**Comment by ashawley** [comment]
Thanks for reporting this.  After a long delay, it seems this should be fixed in #370.
