### ISSUE TITLE
Convert draft to post with Rake task

### ISSUE THREAD

**Issue by pardahlman** [johno/pixyll#310]
Awesome job with this theme 👌 

I see that you have plenty of things in your backlog, but one thing that I think would be super handy is if there were some kind of Rake task for converting a draft to a post. Preferably, it would move the draft to the `_posts` directory and append todays date to the file name. It would be _even better_ if it could update the `date` header of the post.

Keep up the good work!

**Comment by Calavoow** [comment]
Check the `future` flag in the Jekyll configuration docs: https://jekyllrb.com/docs/configuration/
Maybe it can do what you want.
