### ISSUE TITLE
Add active styling to the current link in nav

### ISSUE THREAD

**Issue by johno** [johno/pixyll#367]
Perhaps a light bottom border?

**Comment by ashawley** [comment]
Light bottom border on the nav link for the current page sounds good to me.  Was this what you had in mind?

![current page in nav with light underline](https://user-images.githubusercontent.com/358615/51292429-ad24a100-19d8-11e9-8aab-b96e329949e6.png)

**Comment by johno** [comment]
Exactly, love it <3

**Comment by ashawley** [comment]
Ok, cool.  Let me share what I have come up.
