### ISSUE TITLE
Make old tags

### ISSUE THREAD

**Issue by ashawley** [johno/pixyll#372]
John,

I was thinking of publishing the following version tags since the last release, v2.9.0.  I wasn't sure if you had some tags locally you hadn't pushed, or if you had opinions on version policy.  If and when I finish the Gem work in #334 and we start publishing gems, versions will be important for tracking the changes, so it would be nice to keep them going as you had been.

Thanks,
Aaron

ddb69254 v2.9.1
- made integration of mathjax protocol aware
- Merge pull request #349 from dittodhole/hotfix/relative-protocol-for-mathjax

02b72b63 v2.10.0
- Use plugins instead of gems in config
- Merge pull request #353 from nbau21/gems-to-plugins
- Add .travis.yml
- Fix build warning in index.html layout
- Merge pull request #355 from ashawley/travis-ci
- Merge pull request #356 from ashawley/liquid-warning

4fbfb873 v2.10.1
- Add PR instructions
- Correct wording slightly
- Create PULL_REQUEST_TEMPLATE.md
- Fix link button hover border
- Merge pull request #345 from davejm/fix-link-button-hover-border
- Update Pull Request Template and revert readme
- Merge pull request #336 from plttn/master
- PR template tweaks
- This was a long lived typo : (

ded27eae v2.10.2
- Fix invalid property
- Merge pull request #359 from Wilfred/patch-1

**Comment by johno** [comment]
Thanks @ashawley. If I had any tags floating around they'd now be on an old machine, so feel free to publish those tags if you'd like. My only opinions on versioning are abiding to semver : )

For future releases it'd be great to start publishing tags + a GitHub release with a quick summary as you've done so here 👍.

**Comment by ashawley** [comment]
Cool, thanks.  I agree on semver and agree that there should be release notes.
