### ISSUE TITLE
Link tag in header without ending ">"

### ISSUE THREAD

**Issue by djfoxer** [johno/pixyll#376]
https://github.com/johno/pixyll/blob/0cdd29598001bcdd06ab35ea2d8421c3b2ffec36/_includes/head.html#L94

Hi. It's my first post here. Few days ago I had updated my pixyll to master version and I found that there is no ending `>` for `link` and script for Google analytics is rendered and not taken as a js script.

**Comment by ashawley** [comment]
Sorry about that. This was my mistake.  😢   

This has been fixed in #377.

Thanks for diagnosing your issue and reporting it.
