### ISSUE TITLE
Python code syntax highlighting is a bit weird

### ISSUE THREAD

**Issue by thedch** [johno/pixyll#397]
Hi, and thank you for such an excellent theme!

The Python syntax highlighting is a bit weird -- see https://thedch.github.io/technical/2018/11/23/tensorflow-lite-rpi/

screenshot:
<img width="873" alt="screen shot 2019-02-14 at 10 09 55 am" src="https://user-images.githubusercontent.com/13357734/52807597-cef95e00-3040-11e9-9407-2a5563455524.png">

the code and the comments are the same color, which is kind of hard to read. compare to github syntax highlighting:

```python
import numpy as np
import tensorflow as tf
from tqdm import tqdm

x_test, y_test = ... # load your dataset in here

# Load TFLite model and allocate tensors
interpreter = tf.contrib.lite.Interpreter(model_path="mnist_model.tflite")
interpreter.allocate_tensors()
```

I would be happy to submit a PR fixing this if you could give me some pointers as to which files to check out. I thought maybe `./_sass/_code.scss`, but it does not look like the right file... let me know, thanks!

**Comment by ashawley** [comment]
We'd ❤️ a PR.  I believe it might be the `$hljs-comment` line in `_variables.scss`.  

Yeah, hopefully it's just a styling issue.  😎 

If it's a parsing issue, then it could be an issue upstream of Pixyll, specically with the [Rouge highlighter](http://rouge.jneen.net/).

**Comment by thedch** [comment]
After some inspect element digging, my solution (for any future curious readers) is to change 

```
code {
  color: #7a7a7a;
}
```

in `./_sass/_code.scss`

to 

```
code {
  color: #333;
}
```

(aka `$dark-gray: #333 !default;` from `_variables.scss`). I'm not sure how this impacts languages besides Python -- I'll try a few out and submit a PR if it seems to be a generally better change.

**Comment by alxmjo** [comment]
I know this is closed, but FWIW I find the recommended change (to` #333`) looks much better in C++, too.
