### ISSUE TITLE
New posts are not placed in the correct directory

### ISSUE THREAD

**Issue by connormcdermid** [johno/pixyll#414]
When running with a clean build, the posts that have been placed there by Pixyll developers in _posts are built and moved to` _site/jekyll/pixyll/year/month/day/title/index.html`, however new posts added by myself are built and moved to `_site/year/month/day/title/index.html`, where they are not indexed by paginator or Jekyll, and as such are not put on the front page.

Is there a configuration option to change post build directories, or any other workaround available?

**Comment by ashawley** [comment]
After cloning the repo, I use the rake task to create a new post:

```
$ rake 'post[Hello\, world]'
Creating new post: _posts/2020-03-13-hello-world.md
$ bundle exec jekyll s 
Configuration file: /path/to/pixyll/_config.yml
            Source: /path/to/pixyll
       Destination: /path/to/pixyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 2.295 seconds.
 Auto-regeneration: enabled for '/path/to/pixyll'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

It works for me.

Are you seeing any errors?

**Comment by ashawley** [comment]
Are you using Chrome?  I'm seeing a similar problem.  I wonder if #417 is the issue.  Alternatively, we may just need to disable the service worker for local development.

**Comment by connormcdermid** [comment]
I used `rake draft[]` and `rake undraft[]` to create posts. Posts would not be displayed, but then when I checked the site a few hours later, they were there. I think it's a time/date issue on my end, and I'll try to wrap that up.

I was using Firefox, not Chrome.

**Comment by ashawley** [comment]
I assumed it had to do with local development, but it sounds like your issue was with publishing.  Do you publish to GitHub pages?  I've found there is an occasional delay, but it's never very long.
