### ISSUE TITLE
Forked site does not load Jekyll Theme

### ISSUE THREAD

**Issue by reikdas** [johno/pixyll#422]
My fork does not load the Jekyll Theme - https://reikdas.github.io/DailyBlog/

**Comment by ashawley** [comment]
Sorry to hear that.  Yes, forking the repo is tricky for some.

Did you see this section in the README: https://github.com/johno/pixyll#a-configuration-tweak-if-youre-using-a-gh-pages-sub-folder

**Comment by reikdas** [comment]
Yes, in this commit - https://github.com/reikdas/DailyBlog/commit/0e24454d7bca31f9a7d2437ad7583be24a7d6dcd

**Comment by ashawley** [comment]
I'm afraid I'm not sure what else it could be.

**Comment by reikdas** [comment]
Strangely, it is not even just my fork that faces this issue. I took a look at 2-3 forks of this repository from the [GitHub Network page](https://github.com/johno/pixyll/network/members) and I found another fork similarly broken - https://cecilaki.github.io/blog-outiller-cafdo/

**Comment by plttn** [comment]
It might be Github being weird then.

https://cecilaki.github.io/blog-outiller-cafdo/ -- doesn't work for me

https://reikdas.github.io/DailyBlog/ -- does work for me

![image](https://user-images.githubusercontent.com/7369280/81600544-a57fcd00-937e-11ea-81b6-7466317be00b.png)

**Comment by reikdas** [comment]
https://reikdas.github.io/DailyBlog/ works for me now as well. Must have just been something with GitHub.. Thanks!
