### ISSUE TITLE
Как мне забрать мой сайт когда то просил его переделать для гитхаба..

### ISSUE THREAD

**Issue by KenyaLS** [johno/pixyll#425]
Как мне забрать мой сайт? когда то просил его переделать для гитхаба.. Уважаемые люди помогите мне утеряна логин для связи.

**Comment by plttn** [comment]
переводчик Google

Эта страница не имеет ничего общего с информацией для входа в систему или возможностью доступа к любой информации для входа в систему в любом месте.

**Comment by KenyaLS** [comment]
Данный сайт нарушает мои прова владельца сайт хостинг(репозитория) идет на эту страницу также дезинформирует лет так 10. Я только обратил внимание.

**Comment by KenyaLS** [comment]
Я смотрю ты радасны и не голодный

**Comment by KenyaLS** [comment]
> переводчик Google
> 
> Эта страница не имеет ничего общего с информацией для входа в систему или возможностью доступа к любой информации для входа в систему в любом месте.

Сука, это мой сайт вы откыртом доступе гитхаба..
