### ISSUE TITLE
Здравствуйте закройте сайт https://cmusphinx.github.io/ . Уважаемые я пишу сдруго аккаунта.

### ISSUE THREAD

**Issue by KenyaLS** [johno/pixyll#427]
Здравствуйте закройте сайт https://cmusphinx.github.io/ . Уважаемые я пишу сдруго аккаунта.

**Comment by plttn** [comment]
This repository has nothing to do with that site.

I cannot tell if:
- You believe that website has stolen your content
- this repo has stolen your content
- or another scenario

in any case, there is nothing that can be done here for you.

---

Этот репозиторий не имеет ничего общего с этим сайтом.

Я не могу сказать, если:
- Вы считаете, что веб-сайт украл ваш контент
- этот репо украл ваш контент
- или другой сценарий

в любом случае, здесь ничего нельзя сделать для вас.
